# Generated by Django 4.2.3 on 2023-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publicationdate',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Content', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
